### ISSUE TITLE
Will this work with the new THRII?

### ISSUE THREAD

**Issue by Prof-Rubik** [MathisRosenhauer/THR_Footswitch#1]
Hi, I was wondering if this would work with the new Yamaha THRII. From looking at the difference in the editing programs for these amps there is quite a difference but I was also wondering if one would be able to send a midi message just to change on the onboard present between the five options and maybe engage the tuner?

**Comment by MathisRosenhauer** [comment]
I don't own a THRII so I don't know. From what I read they are more like Line 6 gear USB-wise. If they still support USB 1.x, you might be able to talk to one with the hardware I used. Maybe some of the people who already did some reverse engineering for the THRII know more. You would probably find them on The Gear Page or on yamahamusicians.

**Comment by Prof-Rubik** [comment]
thanks!
