### ISSUE TITLE
THR_Footswitch doesn't work with THRII

### ISSUE THREAD

**Issue by Viser** [MathisRosenhauer/THR_Footswitch#2]
Unfortunately THR_Footswitch doesn't work with THRII.
For THRII new format of patches has been created 'thrl6p' which is basically XML not binary like for TRH.
Without converter to PROGMEM I don't know how to test switch itself.
Another thing I would like to mention is that TRHII doesn't work with TRH editor v 1.1.0, all presets currently could be loaded via TRH Remote.

**Comment by MathisRosenhauer** [comment]
I don't own a THR10II so all I know about it is stuff I've read somewhere. Even though it also uses MIDI SysEx over USB to communicate, the messages are different. I don't even know if it still supports full speed USB which is all the Host shield can deliver. To make a device similar to the one here for the THR10II, you probably have to start from scratch.

**Comment by Viser** [comment]
Thanks for advice! I've just finished the [prototype](https://github.com/Viser/THRII_presets_footswitch/blob/main/thr_preset_switch.ino) with same HW as yours, for now it just able to switch presets since that's all I need.

**Comment by MathisRosenhauer** [comment]
Great you got it working :+1:
